/* Generated from web/index.html; GPL-3.0-or-later. */
static const char clock_web_ui[] =
"<!-- Copyright (C) 2026 Steve Madden | SPDX-License-Identifier: GPL-3.0-or-later -->\n"
"<!doctype html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"  <meta charset=\"utf-8\">\n"
"  <meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
"  <title>WiFi-Clock Setup</title>\n"
"  <link rel=\"icon\" href=\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'%3E%3Ctext y='.9em' font-size='90'%3E%F0%9F%95%92%3C/text%3E%3C/svg%3E\">\n"
"  <style>\n"
"    .firmwareVersion a:link,.firmwareVersion a:visited,.firmwareVersion a:hover,.firmwareVersion a:focus,.firmwareVersion a:active{color:inherit;font-weight:inherit;text-decoration:none}\n"
"    :root{color-scheme:light;--ink:#253044;--muted:#596579;--line:#65758d24;--blue:#345487;--blue-dark:#274371;--red:#963747;--red-dark:#7c2938;--ok:#276b50}\n"
"    *{box-sizing:border-box}html{min-height:100%;background:radial-gradient(ellipse at 5% 0%,#e7e5f8 0,transparent 52%),radial-gradient(ellipse at 100% 35%,#f7e8e5 0,transparent 48%),radial-gradient(ellipse at 0% 100%,#dfefea 0,transparent 50%),#f2f5fa}body{max-width:680px;margin:auto;padding:24px 20px;color:var(--ink);font:16px/1.45 -apple-system,BlinkMacSystemFont,\"Segoe UI\",sans-serif;-webkit-font-smoothing:antialiased}\n"
"    header{padding:8px 4px 18px}h1{margin:0;font-size:1.9rem;font-weight:650;letter-spacing:-.035em}h2{margin:0;font-size:1.05rem;font-weight:650;letter-spacing:-.015em}p{margin:8px 0;color:var(--muted)}\n"
"    .card{margin:10px 0;padding:24px;border:1px solid #ffffffd9;border-radius:22px;background:#ffffffb8;-webkit-backdrop-filter:blur(18px) saturate(115%);backdrop-filter:blur(18px) saturate(115%);box-shadow:0 16px 48px #3543640b,0 2px 8px #35436406,inset 0 1px 0 #ffffffed}\n"
"    header.card{margin:0 0 16px;padding:22px 24px}\n"
"    .settingsGroup{padding:0 0 22px;margin-bottom:22px;border-bottom:1px solid var(--line)}.sectionHeading{display:flex;align-items:center;justify-content:space-between;gap:12px}.sectionHeading .small{margin:0}.sectionHeading button{width:auto;margin:0;font-size:.85rem;min-height:36px;padding:6px 10px}.help{margin:8px 0 0}.resetOptions{margin-top:20px;border-top:1px solid var(--line);padding-top:15px}.resetOptions summary{cursor:pointer;color:var(--muted);font-size:.88rem}.resetOptions button{width:auto;font-size:.9rem;padding:8px 14px}\n"
"    .status{display:inline-flex;align-items:center;gap:9px;margin-top:12px;padding:7px 12px;border:1px solid #ffffffc4;border-radius:100px;background:#ffffff85;font-size:.88rem;font-weight:550;box-shadow:0 2px 8px #35436405}.dot{flex-shrink:0;width:8px;height:8px;border-radius:50%;background:#8793a5}.dot.online{background:#408767;box-shadow:0 0 0 3px #40876716}.dot.portal{background:#bb883b;box-shadow:0 0 0 3px #bb883b16}.hidden{display:none}.small{font-size:.86rem}.firmwareVersion{margin-top:18px;text-align:center;color:#657084;font-size:.78rem}a{color:var(--blue);font-weight:600}\n"
"    label{display:block;margin-top:15px;font-size:.9rem;font-weight:550}input,select,button{width:100%;min-height:44px;margin-top:6px;border:1px solid #75839b38;border-radius:12px;padding:10px 12px;background:#ffffffab;color:inherit;font:inherit;font-weight:400;box-shadow:inset 0 1px 0 #ffffffc9,0 2px 5px #35436404}input::placeholder{color:#657084;opacity:1}input:focus,select:focus{outline:3px solid #557ab847;border-color:#557ab8}button:focus-visible,summary:focus-visible,a:focus-visible{outline:3px solid #557ab86b;outline-offset:3px}\n"
"    .row{display:grid;grid-template-columns:1fr 1fr;gap:12px}button{cursor:pointer;background:linear-gradient(180deg,#e6edff,#dbe5fa);color:var(--blue-dark);font-weight:650;border-color:#c4d3ed;box-shadow:0 3px 10px #45679c0c,inset 0 1px 0 #ffffffcf;transition:background-color .15s,border-color .15s}button:hover{background:#d6e1f7;border-color:#adc2e3}button:disabled{opacity:.6;cursor:wait}button.secondary{background:#ffffff94;color:var(--blue);border-color:#75839b30;font-weight:550}button.secondary:hover{background:#eaf0fc}button.danger{margin-top:10px;border-color:#d9abb448;background:#f6e6e9;color:var(--red);box-shadow:none}button.danger:hover{background:#efd6dc;color:var(--red-dark)}.notice{min-height:1.4em;margin-top:14px;font-size:.9rem}.notice.ok{color:var(--ok)}.notice.bad{color:var(--red)}\n"
"    @supports not ((backdrop-filter:blur(1px)) or (-webkit-backdrop-filter:blur(1px))){.card{background:#f9fafdf5}}\n"
"    @media(prefers-reduced-transparency:reduce){.card{background:#f9fafd;-webkit-backdrop-filter:none;backdrop-filter:none}.status,input,select{background:#fff}}\n"
"    @media(prefers-reduced-motion:reduce){button{transition:none}}\n"
"    .notice:empty{display:none}\n"
"    input,select{background:#ffffffed;border-color:#a7b3c8;box-shadow:inset 0 1px 2px #35436406,0 1px 2px #35436405}\n"
"    input:hover,select:hover{border-color:#899bb8}\n"
"    input:focus,select:focus{background:#fff;border-color:#557ab8}\n"
"    .updateTime{border:0;padding:0;margin:18px 0 0;min-width:0}.updateTime legend{font-size:.9rem;font-weight:550;padding:0}.timeFields{display:grid;grid-template-columns:1fr 1fr;gap:12px}.timeFields label{margin-top:7px;color:var(--muted);font-size:.82rem}.settingsGroup:last-of-type{padding-bottom:0;border-bottom:0}.help{line-height:1.5}\n"
"    @media(max-width:480px){body{padding:16px 14px}.row{grid-template-columns:1fr}.card{padding:19px 17px;border-radius:18px}header.card{padding:19px 17px}h1{font-size:1.8rem}}\n"
"  </style>\n"
"</head>\n"
"<body>\n"
"  <header class=\"card\">\n"
"    <h1 id=\"mainTitle\">WiFi-Clock Setup</h1>\n"
"    <div class=\"status\"><span id=\"dot\" class=\"dot\"></span><span id=\"state\">Checking clock status\342\200\246</span></div>\n"
"    <p id=\"localAddress\" class=\"small hidden\"></p>\n"
"  </header>\n"
"\n"
"  <section class=\"card\">\n"
"    <section class=\"settingsGroup\" aria-labelledby=\"wifiHeading\">\n"
"    <div class=\"sectionHeading\"><h2 id=\"wifiHeading\">Wi-Fi <span class=\"small\">\302\267 2.4 GHz</span></h2><button class=\"secondary\" id=\"scan\">Re-scan</button></div>\n"
"    <label for=\"networks\">Available Wi-Fi networks</label>\n"
"    <select id=\"networks\"><option value=\"\">Select a network</option><option value=\"manual\">Enter manually / hidden SSID</option></select>\n"
"    <div id=\"ssidRow\" class=\"hidden\"><label for=\"ssid\">Manually enter Network name (SSID)</label><input id=\"ssid\" maxlength=\"32\" autocomplete=\"off\" placeholder=\"Enter a Wi-Fi network name\"></div>\n"
"    <label for=\"password\">Wi-Fi password</label>\n"
"    <input id=\"password\" type=\"password\" maxlength=\"63\" autocomplete=\"current-password\" placeholder=\"Leave blank for open Wi-Fi\">\n"
"    </section>\n"
"    <section class=\"settingsGroup\" aria-labelledby=\"timeHeading\">\n"
"    <h2 id=\"timeHeading\">Time</h2>\n"
"    <label for=\"timezonePreset\">Timezone<select id=\"timezonePreset\"></select></label>\n"
"    <label for=\"dstMode\">Daylight saving<select id=\"dstMode\"><option value=\"automatic\">Automatic</option><option value=\"disabled\">Disabled</option><option value=\"custom\">Custom rule</option></select></label>\n"
"    <div id=\"customTimezoneRow\" class=\"hidden\"><label for=\"customTimezone\">Custom POSIX rule</label><input id=\"customTimezone\" maxlength=\"64\" autocomplete=\"off\" placeholder=\"GMT0BST,M3.5.0/1,M10.5.0/2\"></div>\n"
"    <p id=\"nextDst\" class=\"small help hidden\" aria-live=\"polite\"></p>\n"
"    <fieldset class=\"updateTime\" aria-describedby=\"updateHelp\"><legend>Daily update time</legend><div class=\"timeFields\">\n"
"      <label for=\"syncHour\">Hour<select id=\"syncHour\"></select></label>\n"
"      <label for=\"syncMinute\">Minute<select id=\"syncMinute\"><option value=\"00\">00</option><option value=\"10\">10</option><option value=\"20\">20</option><option value=\"30\">30</option><option value=\"40\">40</option><option value=\"50\">50</option></select></label>\n"
"    </div></fieldset>\n"
"    <p id=\"updateHelp\" class=\"small help\">Clock local time, in 10-minute steps.</p>\n"
"    </section>\n"
"    <section class=\"settingsGroup\" aria-labelledby=\"serversHeading\">\n"
"    <h2 id=\"serversHeading\">Time servers</h2>\n"
"    <div class=\"row\">\n"
"      <label for=\"ntpHost\">Primary NTP server<input id=\"ntpHost\" maxlength=\"127\" autocomplete=\"off\" placeholder=\"pool.ntp.org\"></label>\n"
"      <label for=\"ntpBackupHost\">Secondary NTP server<input id=\"ntpBackupHost\" maxlength=\"127\" autocomplete=\"off\" placeholder=\"time.cloudflare.com\"></label>\n"
"    </div>\n"
"    <p class=\"small help\">The secondary is tried after 5 seconds; the first valid reply wins. Leave blank to use the defaults shown.</p>\n"
"    </section>\n"
"    <section class=\"settingsGroup\" aria-labelledby=\"handsHeading\">\n"
"    <h2 id=\"handsHeading\">Hand movement</h2>\n"
"    <label for=\"handMovement\">Movement style</label>\n"
"    <select id=\"handMovement\" aria-describedby=\"movementHelp\"><option value=\"sweep\">Sweep</option><option value=\"burst\">Burst</option><option value=\"hold_start\">Hold&amp;Start</option></select>\n"
"    <p id=\"movementHelp\" class=\"small help\">Seconds sweep continuously; the minute hand advances gradually.</p>\n"
"    <label for=\"nightParking\">Second hand battery saver<select id=\"nightParking\" aria-describedby=\"parkingHelp\"><option value=\"off\">Off</option><option value=\"night\">Night parking</option><option value=\"on\">On</option></select></label>\n"
"    <p id=\"parkingHelp\" class=\"small help\">Night parking: parks at 12 from 00:00 to 06:00. On: parks at 12 continuously. Use On if no second hand is fitted to prolong battery life.</p>\n"
"    </section>\n"
"    <button id=\"sendTime\">Save settings</button>\n"
"    <p id=\"notice\" class=\"notice\" role=\"status\" aria-live=\"polite\"></p>\n"
"    <details class=\"resetOptions\" id=\"resetOptions\"><summary>Reset settings</summary><p class=\"small\">Erase saved settings and return to Wi-Fi setup.</p><button class=\"danger\" id=\"factoryReset\">Erase settings</button></details>\n"
"  </section>\n"
"  <p class=\"small firmwareVersion\"><a id=\"projectLink\" href=\"https://github.com/maddenste/Chouchin-899-latest-revision\" target=\"_blank\" rel=\"noopener noreferrer\"><span id=\"firmwareVersion\">WiFi Clock \302\267 v2.0</span> \342\200\224 Modified by Steve Madden \302\267 2026</a></p>\n"
"\n"
"  <script>\n"
"    const $ = id => document.getElementById(id);\n"
"    const DEFAULT_NTP = 'pool.ntp.org';\n"
"    const DEFAULT_NTP_BACKUP = 'time.cloudflare.com';\n"
"    const DEFAULT_TZ = 'GMT0BST,M3.5.0/1,M10.5.0/2';\n"
"    // [id, label, fixed-standard-time rule, automatic rule]. Automatic rules\n"
"    // were checked against current IANA data from 2026-09-10 through 2035.\n"
"    const TIMEZONE_PRESETS = [\n"
"      ['baker','(UTC-12:00) Baker Island','<-12>12','<-12>12'],\n"
"      ['american_samoa','(UTC-11:00) American Samoa','SST11','SST11'],\n"
"      ['honolulu','(UTC-10:00) Honolulu','HST10','HST10'],\n"
"      ['anchorage','(UTC-09:00) Anchorage','AKST9','AKST9AKDT,M3.2.0,M11.1.0'],\n"
"      ['los_angeles','(UTC-08:00) Los Angeles','PST8','PST8PDT,M3.2.0,M11.1.0'],\n"
"      ['phoenix_vancouver','(UTC-07:00) Phoenix, Vancouver','MST7','MST7'],\n"
"      ['denver','(UTC-07:00) Denver','DEN7','MST7MDT,M3.2.0,M11.1.0'],\n"
"      ['chicago','(UTC-06:00) Chicago','CHI6','CST6CDT,M3.2.0,M11.1.0'],\n"
"      ['mexico_city','(UTC-06:00) Mexico City','CST6','CST6'],\n"
"      ['new_york','(UTC-05:00) New York','EST5','EST5EDT,M3.2.0,M11.1.0'],\n"
"      ['lima','(UTC-05:00) Lima','<-05>5','<-05>5'],\n"
"      ['halifax','(UTC-04:00) Halifax','AST4','AST4ADT,M3.2.0,M11.1.0'],\n"
"      ['santiago','(UTC-04:00) Santiago','<-04>4','<-04>4<-03>,M9.1.6/24,M4.1.6/24'],\n"
"      ['newfoundland','(UTC-03:30) Newfoundland','NST3:30','NST3:30NDT,M3.2.0,M11.1.0'],\n"
"      ['buenos_aires','(UTC-03:00) Buenos Aires','<-03>3','<-03>3'],\n"
"      ['south_georgia','(UTC-02:00) South Georgia','<-02>2','<-02>2'],\n"
"      ['azores','(UTC-01:00) Azores','<-01>1','<-01>1<+00>,M3.5.0/0,M10.5.0/1'],\n"
"      ['utc_reykjavik','(UTC+00:00) UTC / Reykjavik','UTC0','UTC0'],\n"
"      ['london','(UTC+00:00) London (GMT/BST)','GMT0','GMT0BST,M3.5.0/1,M10.5.0/2'],\n"
"      ['paris_berlin','(UTC+01:00) Paris, Berlin','CET-1','CET-1CEST,M3.5.0,M10.5.0/3'],\n"
"      ['athens','(UTC+02:00) Athens','EET-2','EET-2EEST,M3.5.0/3,M10.5.0/4'],\n"
"      ['johannesburg','(UTC+02:00) Johannesburg','SAST-2','SAST-2'],\n"
"      ['moscow_nairobi','(UTC+03:00) Moscow, Nairobi','MSK-3','MSK-3'],\n"
"      ['tehran','(UTC+03:30) Tehran','<+0330>-3:30','<+0330>-3:30'],\n"
"      ['dubai','(UTC+04:00) Dubai, Abu Dhabi','<+04>-4','<+04>-4'],\n"
"      ['karachi','(UTC+05:00) Karachi, Islamabad','PKT-5','PKT-5'],\n"
"      ['almaty','(UTC+05:00) Almaty','<+05>-5','<+05>-5'],\n"
"      ['india_sri_lanka','(UTC+05:30) India, Sri Lanka','IST-5:30','IST-5:30'],\n"
"      ['dhaka','(UTC+06:00) Dhaka','<+06>-6','<+06>-6'],\n"
"      ['yangon','(UTC+06:30) Yangon','<+0630>-6:30','<+0630>-6:30'],\n"
"      ['bangkok_jakarta','(UTC+07:00) Bangkok, Jakarta','<+07>-7','<+07>-7'],\n"
"      ['singapore_beijing','(UTC+08:00) Singapore, Beijing','<+08>-8','<+08>-8'],\n"
"      ['tokyo_seoul','(UTC+09:00) Tokyo, Seoul','JST-9','JST-9'],\n"
"      ['darwin','(UTC+09:30) Darwin','ACST-9:30','ACST-9:30'],\n"
"      ['sydney_melbourne','(UTC+10:00) Sydney, Melbourne','AEST-10','AEST-10AEDT,M10.1.0,M4.1.0/3'],\n"
"      ['solomon','(UTC+11:00) Solomon Islands','<+11>-11','<+11>-11'],\n"
"      ['auckland','(UTC+12:00) Auckland','NZST-12','NZST-12NZDT,M9.5.0,M4.1.0/3'],\n"
"      ['fiji','(UTC+12:00) Fiji','<+12>-12','<+12>-12'],\n"
"      ['samoa_tonga','(UTC+13:00) Samoa, Tonga','<+13>-13','<+13>-13'],\n"
"      ['kiritimati','(UTC+14:00) Kiritimati','<+14>-14','<+14>-14']\n"
"    ];\n"
"    let savedSsid = '', hasSavedPassword = false;\n"
"    for (let hour = 0; hour < 24; ++hour) {\n"
"      const value = String(hour).padStart(2, '0');\n"
"      $('syncHour').add(new Option(value, value));\n"
"    }\n"
"    let requestToken = '';\n"
"    // A page identity, not an authentication secret. The TXW supplies the\n"
"    // independent per-boot anti-forgery token when configuration is loaded.\n"
"    const pageId = Array.from({length: 4}, () => Math.floor(Math.random() * 0x100000000).toString(16).padStart(8, '0')).join('');\n"
"    let leaving = false, scanBusy = false, actionBusy = false, configLoaded = false;\n"
"    let webSessionStarted = false, heartbeatBusy = false, statusBusy = false;\n"
"    let heartbeatTimer, statusTimer;\n"
"    let latestDstStatus = null;\n"
"    let dstPreview = null, dstTimer, dstBusy = false, dstRevision = 0;\n"
"    const notice = (text, kind = '') => {\n"
"      $('notice').textContent = text;\n"
"      $('notice').className = 'notice ' + kind;\n"
"    };\n"
"    // Bound every request so a sleeping clock cannot accumulate pending polls.\n"
"    async function request(url, options = {}) {\n"
"      const controller = new AbortController();\n"
"      const timer = setTimeout(() => controller.abort(), options.method === 'POST' ? 30000 : 6000);\n"
"      try {\n"
"        const headers = {...options.headers};\n"
"        if (requestToken) headers['X-Clock-Token'] = requestToken;\n"
"        const response = await fetch(url, {...options, headers, cache: 'no-store', signal: controller.signal});\n"
"        const data = response.status === 204 ? {} : await response.json();\n"
"        if (!response.ok) {\n"
"          const error = Error(data.error || 'The clock could not complete the request.');\n"
"          error.status = response.status;\n"
"          throw error;\n"
"        }\n"
"        return data;\n"
"      } finally {\n"
"        clearTimeout(timer);\n"
"      }\n"
"    }\n"
"    function setStatus(status) {\n"
"      latestDstStatus = status;\n"
"      showNextDst();\n"
"      if (typeof status.firmwareVersion === 'string' && status.firmwareVersion) {\n"
"        $('firmwareVersion').textContent = status.firmwareVersion;\n"
"        $('firmwareVersion').title = status.buildId || '';\n"
"      }\n"
"      const localAddress = $('localAddress');\n"
"      if (status.mode === 'station' && typeof status.mdnsHost === 'string' && status.mdnsHost) {\n"
"        localAddress.textContent = 'Local address: http://' + status.mdnsHost + '/';\n"
"        localAddress.className = 'small';\n"
"      } else {\n"
"        localAddress.textContent = '';\n"
"        localAddress.className = 'small hidden';\n"
"      }\n"
"      if (status.mode === 'portal') {\n"
"        $('dot').className = 'dot portal';\n"
"        $('state').textContent = 'Setup active \302\267 ' + status.ip;\n"
"      } else if (status.mode === 'station') {\n"
"        $('dot').className = status.connected ? 'dot online' : 'dot';\n"
"        $('state').textContent = status.connected\n"
"          ? (status.timeSynced ? 'Time synchronised \302\267 ' : 'Connected \302\267 waiting for time \302\267 ') + status.ip\n"
"          : 'Connecting to Wi-Fi\342\200\246';\n"
"      } else {\n"
"        $('dot').className = 'dot';\n"
"        $('state').textContent = 'Clock connection unavailable';\n"
"      }\n"
"    }\n"
"    async function refreshStatus() {\n"
"      if (leaving || statusBusy) return;\n"
"      statusBusy = true;\n"
"      try {\n"
"        const status = await request('/api/v1/status');\n"
"        if (!leaving) setStatus(status);\n"
"      } catch (error) {\n"
"        if (!leaving) {\n"
"          latestDstStatus = null;\n"
"          showNextDst();\n"
"          $('dot').className = 'dot';\n"
"          $('state').textContent = 'Clock connection lost';\n"
"          $('localAddress').textContent = '';\n"
"          $('localAddress').className = 'small hidden';\n"
"        }\n"
"      } finally {\n"
"        statusBusy = false;\n"
"      }\n"
"    }\n"
"    function updatePasswordHint() {\n"
"      $('password').placeholder = hasSavedPassword && $('ssid').value === savedSsid\n"
"        ? 'Leave blank to keep the saved password'\n"
"        : 'Leave blank for open Wi-Fi';\n"
"    }\n"
"    function populateTimezonePresets() {\n"
"      const menu = $('timezonePreset');\n"
"      for (const preset of TIMEZONE_PRESETS) menu.add(new Option(preset[1], preset[0]));\n"
"      menu.value = 'london';\n"
"    }\n"
"    function selectedTimezonePreset() {\n"
"      return TIMEZONE_PRESETS.find(preset => preset[0] === $('timezonePreset').value) ||\n"
"        TIMEZONE_PRESETS.find(preset => preset[0] === 'london');\n"
"    }\n"
"    function selectedTimezoneRule() {\n"
"      if ($('dstMode').value === 'custom') return $('customTimezone').value.trim();\n"
"      const preset = selectedTimezonePreset();\n"
"      return preset[$('dstMode').value === 'disabled' ? 2 : 3];\n"
"    }\n"
"    function showNextDst() {\n"
"      const revision = ++dstRevision, rule = selectedTimezoneRule();\n"
"      clearTimeout(dstTimer);\n"
"      const eligible = configLoaded && !leaving && $('dstMode').value !== 'disabled';\n"
"      const status = dstPreview && dstPreview.rule === rule ? dstPreview.data :\n"
"        latestDstStatus && latestDstStatus.timezone === rule ? latestDstStatus : null;\n"
"      renderNextDst(eligible ? status : null);\n"
"      if (!eligible) return;\n"
"      dstTimer = setTimeout(async () => {\n"
"        if (dstBusy) return; // The active request will refresh the latest edit.\n"
"        dstBusy = true;\n"
"        try {\n"
"          const data = await request('/api/v1/dst-preview', {\n"
"            method: 'POST', headers: {'Content-Type':'application/x-www-form-urlencoded'},\n"
"            body: new URLSearchParams({timezone:rule})\n"
"          });\n"
"          if (revision === dstRevision && !leaving) {\n"
"            dstPreview = {rule, data};\n"
"            renderNextDst(data);\n"
"          }\n"
"        } catch (error) {\n"
"          if (revision === dstRevision && !leaving) {\n"
"            dstPreview = null;\n"
"            renderNextDst(null);\n"
"            if (error.status === 400) {\n"
"              $('nextDst').classList.remove('hidden');\n"
"              $('nextDst').textContent = error.message;\n"
"            }\n"
"          }\n"
"        } finally {\n"
"          dstBusy = false;\n"
"          if (revision !== dstRevision && !leaving) showNextDst();\n"
"        }\n"
"      }, 250);\n"
"    }\n"
"    function renderNextDst(status) {\n"
"      const line = $('nextDst');\n"
"      const change = status && status.nextDst;\n"
"      const visible = status && status.timeSynced &&\n"
"        change && Number.isFinite(change.utc) && Number.isFinite(change.before) && Number.isFinite(change.after);\n"
"      line.classList.toggle('hidden', !visible);\n"
"      line.textContent = '';\n"
"      if (!visible) return;\n"
"      const before = new Date((change.utc + change.before * 60) * 1000);\n"
"      const after = new Date((change.utc + change.after * 60) * 1000);\n"
"      const date = new Intl.DateTimeFormat('en-GB', {day:'numeric',month:'long',year:'numeric',timeZone:'UTC'});\n"
"      const time = new Intl.DateTimeFormat('en-GB', {hour:'2-digit',minute:'2-digit',hourCycle:'h23',timeZone:'UTC'});\n"
"      line.textContent = 'Next DST change: ' + date.format(before) + ' \342\200\224 ' + time.format(before) + ' \342\206\222 ' + time.format(after);\n"
"    }\n"
"    function loadTimezoneRule(rule) {\n"
"      let preset = TIMEZONE_PRESETS.find(candidate => candidate[3] === rule);\n"
"      if (preset) {\n"
"        $('timezonePreset').value = preset[0];\n"
"        $('dstMode').value = 'automatic';\n"
"        $('customTimezone').value = '';\n"
"        return;\n"
"      }\n"
"      preset = TIMEZONE_PRESETS.find(candidate => candidate[2] === rule);\n"
"      if (preset) {\n"
"        $('timezonePreset').value = preset[0];\n"
"        $('dstMode').value = 'disabled';\n"
"        $('customTimezone').value = '';\n"
"        return;\n"
"      }\n"
"      $('timezonePreset').value = 'london';\n"
"      $('dstMode').value = 'custom';\n"
"      $('customTimezone').value = rule;\n"
"    }\n"
"    function updateControls() {\n"
"      const locked = actionBusy || !configLoaded || leaving;\n"
"      $('ssidRow').classList.toggle('hidden', $('networks').value !== 'manual');\n"
"      $('customTimezoneRow').classList.toggle('hidden', $('dstMode').value !== 'custom');\n"
"      $('movementHelp').textContent = {\n"
"        sweep: 'Seconds sweep continuously; the minute hand advances gradually.',\n"
"        burst: 'Seconds sweep continuously; the minute hand jumps at each minute change.',\n"
"        hold_start: 'Seconds pause at 12, then restart as the minute hand jumps forward.'\n"
"      }[$('handMovement').value];\n"
"      if ($('nightParking').value === 'on') {\n"
"        $('movementHelp').textContent = 'Second hand parks at 12; the minute hand ' +\n"
"          ($('handMovement').value === 'sweep' ? 'advances gradually.' : 'jumps at each minute change.');\n"
"      }\n"
"      for (const id of ['networks', 'ssid', 'password', 'syncHour', 'syncMinute', 'timezonePreset', 'dstMode', 'ntpHost', 'ntpBackupHost', 'handMovement', 'nightParking', 'sendTime']) {\n"
"        $(id).disabled = locked;\n"
"      }\n"
"      $('customTimezone').disabled = locked || $('dstMode').value !== 'custom';\n"
"      showNextDst();\n"
"      $('scan').disabled = locked || scanBusy;\n"
"      $('factoryReset').disabled = locked;\n"
"    }\n"
"    async function load() {\n"
"      updateControls();\n"
"      try {\n"
"        const config = await request('/api/v1/config');\n"
"        if (leaving) return;\n"
"        if (!/^[0-9a-f]{32}$/.test(config.requestToken || '')) throw Error('Reload the clock setup page.');\n"
"        requestToken = config.requestToken;\n"
"        savedSsid = config.ssid || '';\n"
"        hasSavedPassword = config.hasPassword === true;\n"
"        $('ssid').value = savedSsid;\n"
"        if (savedSsid) {\n"
"          $('networks').add(new Option(savedSsid, 'ssid:' + savedSsid));\n"
"          $('networks').value = 'ssid:' + savedSsid;\n"
"        }\n"
"        $('ntpHost').value = config.ntpHost === DEFAULT_NTP ? '' : (config.ntpHost || '');\n"
"        $('ntpBackupHost').value = config.ntpBackupHost === DEFAULT_NTP_BACKUP ? '' : (config.ntpBackupHost || '');\n"
"        loadTimezoneRule(config.timezone || DEFAULT_TZ);\n"
"        const hour = String(config.syncHour ?? 10).padStart(2, '0');\n"
"        const savedMinute = config.syncMinute ?? 0;\n"
"        const minute = String(Math.floor(savedMinute / 10) * 10).padStart(2, '0');\n"
"        $('syncHour').value = hour;\n"
"        $('syncMinute').value = minute;\n"
"        $('updateHelp').textContent = savedMinute % 10\n"
"          ? 'Saved time ' + hour + ':' + String(savedMinute).padStart(2, '0') +\n"
"            ' is shown as ' + hour + ':' + minute + '. Save settings to apply.'\n"
"          : 'Clock local time, in 10-minute steps.';\n"
"        $('handMovement').value = config.secondHand === 'pause_at_12' ? 'hold_start' :\n"
"          (config.minuteHand === 'jump' ? 'burst' : 'sweep');\n"
"        $('nightParking').value = config.nightParking || 'off';\n"
"        configLoaded = true;\n"
"        updatePasswordHint();\n"
"        updateControls();\n"
"        await keepAlive();\n"
"        await scan(true);\n"
"      } catch (error) {\n"
"        if (!leaving) notice('Could not load settings. Reconnect to the clock and refresh this page.', 'bad');\n"
"      }\n"
"    }\n"
"    async function scan(quiet = false) {\n"
"      if (scanBusy || actionBusy || leaving) return;\n"
"      scanBusy = true;\n"
"      updateControls();\n"
"      if (!quiet) notice('Scanning nearby Wi-Fi networks\342\200\246');\n"
"      try {\n"
"        let data = await request('/api/v1/scan?start=1');\n"
"        const started = Date.now();\n"
"        while (data.scanning) {\n"
"          if (leaving || actionBusy) return;\n"
"          if (Date.now() - started > 35000) throw Error('Scan timed out. Enter the network name manually or try again.');\n"
"          await new Promise(resolve => setTimeout(resolve, 750));\n"
"          if (leaving || actionBusy) return;\n"
"          data = await request('/api/v1/scan');\n"
"        }\n"
"        if (leaving || actionBusy) return;\n"
"        const strongest = new Map();\n"
"        for (const network of data.networks) {\n"
"          if (!network.ssid) continue;\n"
"          if (!strongest.has(network.ssid) || strongest.get(network.ssid).rssi < network.rssi) {\n"
"            strongest.set(network.ssid, network);\n"
"          }\n"
"        }\n"
"        const networks = [...strongest.values()].sort((a, b) => b.rssi - a.rssi);\n"
"        const menu = $('networks');\n"
"        const previousSelection = menu.value;\n"
"        menu.length = 0;\n"
"        menu.add(new Option('Select a network', ''));\n"
"        for (const network of networks) {\n"
"          // Prefix values so an actual SSID cannot collide with our manual option.\n"
"          menu.add(new Option(network.ssid === savedSsid ? savedSsid :\n"
"            network.ssid + ' (' + network.rssi + ' dBm)', 'ssid:' + network.ssid));\n"
"        }\n"
"        // A saved hidden/out-of-range network must remain visible and selected.\n"
"        if (savedSsid && !strongest.has(savedSsid)) {\n"
"          menu.add(new Option(savedSsid, 'ssid:' + savedSsid));\n"
"        }\n"
"        menu.add(new Option('Enter manually / hidden SSID', 'manual'));\n"
"        menu.value = quiet ? (savedSsid ? 'ssid:' + savedSsid : '') :\n"
"          ([...menu.options].some(option => option.value === previousSelection) ? previousSelection : '');\n"
"        notice(quiet ? '' : networks.length + ' network(s) found.', 'ok');\n"
"      } catch (error) {\n"
"        if (!leaving && !actionBusy) {\n"
"          notice(error.message || 'Network scan failed. Enter the network name manually.', 'bad');\n"
"        }\n"
"      } finally {\n"
"        scanBusy = false;\n"
"        updateControls();\n"
"      }\n"
"    }\n"
"    $('networks').onchange = event => {\n"
"      if (event.target.value.startsWith('ssid:')) $('ssid').value = event.target.value.slice(5);\n"
"      else if (!event.target.value) $('ssid').value = '';\n"
"      updateControls();\n"
"      if (event.target.value === 'manual') $('ssid').focus();\n"
"      updatePasswordHint();\n"
"    };\n"
"    $('ssid').oninput = updatePasswordHint;\n"
"    $('handMovement').onchange = updateControls;\n"
"    $('nightParking').onchange = updateControls;\n"
"    $('syncHour').onchange = $('syncMinute').onchange = () => {\n"
"      $('updateHelp').textContent = 'Clock local time, in 10-minute steps.';\n"
"    };\n"
"    $('timezonePreset').onchange = showNextDst;\n"
"    $('customTimezone').oninput = showNextDst;\n"
"    $('dstMode').onchange = () => {\n"
"      if ($('dstMode').value === 'custom' && !$('customTimezone').value.trim()) {\n"
"        $('customTimezone').value = selectedTimezonePreset()[3];\n"
"      }\n"
"      updateControls();\n"
"      if ($('dstMode').value === 'custom') $('customTimezone').focus();\n"
"    };\n"
"    $('scan').onclick = () => scan();\n"
"    const settings = () => {\n"
"      const syncHour = $('syncHour').value, syncMinute = $('syncMinute').value;\n"
"      const movement = $('handMovement').value;\n"
"      return new URLSearchParams({\n"
"        ssid: $('ssid').value, password: $('password').value,\n"
"        ntpHost: $('ntpHost').value.trim(), ntpBackupHost: $('ntpBackupHost').value.trim(), timezone: selectedTimezoneRule(),\n"
"        syncHour, syncMinute, minute_hand: movement === 'sweep' ? 'gradual' : 'jump',\n"
"        second_hand: movement === 'hold_start' ? 'pause_at_12' : 'continuous', night_parking: $('nightParking').value\n"
"      });\n"
"    };\n"
"    function stopPolling() {\n"
"      leaving = true;\n"
"      clearInterval(heartbeatTimer);\n"
"      clearInterval(statusTimer);\n"
"      clearTimeout(dstTimer);\n"
"      ++dstRevision;\n"
"    }\n"
"    function showRestart(message) {\n"
"      stopPolling();\n"
"      $('password').value = '';\n"
"      $('dot').className = 'dot';\n"
"      $('state').textContent = 'Clock reconnecting\342\200\246';\n"
"      notice(message, 'ok');\n"
"      updateControls();\n"
"    }\n"
"    $('sendTime').onclick = async () => {\n"
"      if (actionBusy || leaving || !configLoaded) return;\n"
"      if (!$('ssid').value) {\n"
"        notice('Choose a Wi-Fi network or enter its name.', 'bad');\n"
"        ($('networks').value === 'manual' ? $('ssid') : $('networks')).focus();\n"
"        return;\n"
"      }\n"
"      if ($('dstMode').value === 'custom' && !$('customTimezone').value.trim()) {\n"
"        notice('Enter a custom POSIX time-zone rule.', 'bad');\n"
"        $('customTimezone').focus();\n"
"        return;\n"
"      }\n"
"      for (const id of ['ntpHost', 'ntpBackupHost']) {\n"
"        const host = $(id).value.trim();\n"
"        if (host && (host.length > 127 || !/^[A-Za-z0-9-][A-Za-z0-9.-]*$/.test(host) || host.endsWith('.'))) {\n"
"          notice('Enter a hostname or IPv4 address for the ' + (id === 'ntpHost' ? 'primary' : 'secondary') + ' NTP server, without spaces, a URL or a port.', 'bad');\n"
"          $(id).focus();\n"
"          return;\n"
"        }\n"
"      }\n"
"      actionBusy = true;\n"
"      updateControls();\n"
"      notice('Saving settings\342\200\246');\n"
"      try {\n"
"        await request('/api/v1/config', {\n"
"          method: 'POST',\n"
"          headers: {'Content-Type': 'application/x-www-form-urlencoded'},\n"
"          body: settings()\n"
"        });\n"
"        const message = 'Settings saved. The clock will reconnect to Wi-Fi and send time once NTP synchronises. This page may be temporarily unavailable.';\n"
"        showRestart(message + (latestDstStatus && latestDstStatus.mode === 'portal'\n"
"          ? ' Rejoin your usual Wi-Fi network to access the clock.' : ''));\n"
"      } catch (error) {\n"
"        if (!error.status || error.status === 403) stopPolling();\n"
"        notice('Save was not confirmed. Reconnect and check the saved settings before trying again. ' + error.message, 'bad');\n"
"      } finally {\n"
"        actionBusy = false;\n"
"        updateControls();\n"
"      }\n"
"    };\n"
"    $('factoryReset').onclick = async () => {\n"
"      if (actionBusy || leaving) return;\n"
"      if (!confirm('Erase saved Wi-Fi, time-server, time-zone, update-time and hand-movement settings? The clock will return to its setup network.')) return;\n"
"      actionBusy = true;\n"
"      updateControls();\n"
"      try {\n"
"        await request('/api/v1/factory-reset', {method: 'POST'});\n"
"        showRestart('Saved settings erased. Reconnect to the clock setup network. Hand movement defaults to Sweep, with second hand battery saver Off.');\n"
"      } catch (error) {\n"
"        if (!error.status || error.status === 403) stopPolling();\n"
"        notice('Reset was not confirmed. Reconnect to the clock and check. ' + error.message, 'bad');\n"
"      } finally {\n"
"        actionBusy = false;\n"
"        updateControls();\n"
"      }\n"
"    };\n"
"    async function keepAlive() {\n"
"      if (leaving || heartbeatBusy || !requestToken) return;\n"
"      heartbeatBusy = true;\n"
"      try {\n"
"        await request('/api/v1/keepalive', {\n"
"          method: 'POST',\n"
"          headers: {'Content-Type': 'application/x-www-form-urlencoded'},\n"
"          body: new URLSearchParams({start: webSessionStarted ? '0' : '1', page: pageId})\n"
"        });\n"
"        webSessionStarted = true;\n"
"      } catch (error) {\n"
"        // The firmware's session expiry covers lost requests.\n"
"        if (error.status === 403 && !leaving) {\n"
"          stopPolling();\n"
"          notice('This setup page has expired. Reconnect to the clock and refresh it.', 'bad');\n"
"          updateControls();\n"
"        }\n"
"      } finally {\n"
"        heartbeatBusy = false;\n"
"      }\n"
"    }\n"
"    function closeSession() {\n"
"      stopPolling();\n"
"      if (!requestToken) return;\n"
"      const url = '/api/v1/session/close';\n"
"      const body = new URLSearchParams({page: pageId, token: requestToken});\n"
"      if (navigator.sendBeacon && navigator.sendBeacon(url, body)) return;\n"
"      fetch(url, {method: 'POST', body, keepalive: true}).catch(() => {});\n"
"    }\n"
"    addEventListener('pagehide', closeSession);\n"
"    // A page restored from the back/forward cache needs a new browser session.\n"
"    addEventListener('pageshow', event => { if (event.persisted) location.reload(); });\n"
"    populateTimezonePresets();\n"
"    heartbeatTimer = setInterval(keepAlive, 2000);\n"
"    statusTimer = setInterval(refreshStatus, 2000);\n"
"    refreshStatus();\n"
"    load();\n"
"  </script>\n"
"</body>\n"
"</html>\n";
